version: '3'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank-api
    # ports:
    #   - 5432:5432
    # volumes:
    #   - postgres:/var/lib/postgresql/data
  redis:
    image: redis:7.0-alpine

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 9090:9090
    environment:
      DB_SOURCE: "host=postgres port=5432 user=postgres password=postgres dbname=bank-api sslmode=disable"
      REDIS_ADDRESS: "redis:6379"
    depends_on:
      - postgres
      - redis
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/wait-for.sh", "redis:6379", "--", "/app/start.sh" ]
    command: [ "/app/bank-api"]